version: '3.7'

services:
  node-app-1:
    user: root
    restart: always
    build:
      context: .
    ports:
      - "4000-4500:4008"
    volumes:
      - ./images:/usr/src/app/images
    networks:
      - custom_network

networks:
  custom_network:
    external: true
