version: '3.7'

services:
  node-app:
    user: root
    # restart: always
    build:
      context: .
    ports:
      - "4000-4500:4008"
    networks:
      - custom_network

networks:
  custom_network:
    external: true
